language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan gh-pages
    git rm -rf .
    mv public/* .
    rm -rf public master*
    git add -f --ignore-errors --all
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
