language: node_js
    - "8.9.0"

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - npm install gulp
      
before_script:
    - npm install
    - npm install -g gulp-cli
    - |
      if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      export HUGO_ENV=production 
      fi
    
script: 
    - gulp build

after_success: |
    rm -rf node_modules
    if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    git checkout --orphan gh-pages
    mv CNAME.travis CNAME
    git rm -rf .
    mv public/* .
    rm -rf public
    git add -f --ignore-errors --all
    git -c user.name='blafond' -c user.email='blafond' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never
