baseURL: "https://teiid.io/"
languageCode: "en-gb"
title: "Teiid"
theme: "dracoio"
relativeURLs: true
googleAnalytics: "UA-98663114-1"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github

menu:
  topnav:
  - name: "code"
    weight: -110
    identifier: "code"
    url: "https://github.com/teiid"
    
params:
  proddtm: "http://www.redhat.com/dtm.js"
  stagingdtm: "http://www.redhat.com/dtm-staging.js"
