baseURL: "https://teiid.github.io/teiid.io/"
languageCode: "en-gb"
title: "Teiid"
theme: "dracoio"
canonifyURLs: true
googleAnalytics: "UA-98663114-1"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github

menu:
  topnav:
  - name: "code"
    weight: -110
    identifier: "code"
    url: "https://github.com/teiid"
